# Colors
background #20201d
foreground #F7F6F2

color0  #20201D
color1  #F3535E
color2  #3EF47B
color3  #F7F6F2
color4  #A8D0DC
color5  #FFC2C6
color6  #F7F6F2
color7  #F7F6F2

# Font
font_family CaskaydiaCove NFM
font_size 18.0
