#!/bin/bash
source "$HOME/.config/sketchybar/colours.sh"
source "$HOME/.config/sketchybar/icons.sh"
ITEM_DIR="$HOME/.config/sketchybar/items"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
FONT="SF Pro"
PADDINGS=3
HELPER=git.felix.helper

# Start the mach helper for CPU graphs
killall helper 2>/dev/null
cd $HOME/.config/sketchybar/helper && make > /dev/null 2>&1
$HOME/.config/sketchybar/helper/helper $HELPER > /dev/null 2>&1 &

# Unload macOS volume OSD
launchctl unload -F /System/Library/LaunchAgents/com.apple.OSDUIHelper.plist > /dev/null 2>&1 &

# Bar appearance
bar=(
  height=30
  color=$BAR_COLOUR
  shadow=on
  position=top
  sticky=on
  padding_right=25
  padding_left=25
  corner_radius=0
  y_offset=0
  margin=0
  blur_radius=0
  notch_width=0
)
sketchybar --bar "${bar[@]}"

# Defaults
defaults=(
  #updates=when_shown
  icon.font="$FONT:Bold:14.0"
  icon.color=$ICON_COLOUR
  icon.padding_left=$PADDINGS
  icon.padding_right=$PADDINGS
  label.font="$FONT:Semibold:14.0"
  label.color=$LABEL_COLOUR
  label.padding_left=$PADDINGS
  label.padding_right=$PADDINGS
  padding_right=$PADDINGS
  padding_left=$PADDINGS
  background.height=30
  background.corner_radius=9
  popup.background.border_width=2
  popup.background.corner_radius=9
  popup.background.border_color=$POPUP_BORDER_COLOUR
  popup.background.color=$POPUP_BACKGROUND_COLOUR
  popup.blur_radius=20
  popup.background.shadow.drawing=on
)
sketchybar --default "${defaults[@]}"

# Music polling loop
(while true; do
  sleep 2
  sketchybar --trigger music_poll
done) &

# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Center
source "$ITEM_DIR/music.sh"

# Right
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/github.sh"
source "$ITEM_DIR/cpu.sh"

sketchybar --update
echo "sketchybar configuration loaded.."
